/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BetriebRouteImport } from './routes/betrieb'
import { Route as DachbegruenungRouteImport } from './routes/dachbegruenung'
import { Route as DachdeckereiRouteImport } from './routes/dachdeckerei'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as KarriereRouteImport } from './routes/karriere'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ReparaturDachwartungRouteImport } from './routes/reparatur-dachwartung'
import { Route as SekurantenRouteImport } from './routes/sekuranten'
import { Route as SpenglereiRouteImport } from './routes/spenglerei'
import { Route as TaubenabwehrRouteImport } from './routes/taubenabwehr'
import { Route as TeamRouteImport } from './routes/team'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BetriebRoute = BetriebRouteImport.update({
  id: '/betrieb',
  path: '/betrieb',
  getParentRoute: () => rootRouteImport,
} as any)
const DachbegruenungRoute = DachbegruenungRouteImport.update({
  id: '/dachbegruenung',
  path: '/dachbegruenung',
  getParentRoute: () => rootRouteImport,
} as any)
const DachdeckereiRoute = DachdeckereiRouteImport.update({
  id: '/dachdeckerei',
  path: '/dachdeckerei',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const KarriereRoute = KarriereRouteImport.update({
  id: '/karriere',
  path: '/karriere',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ReparaturDachwartungRoute = ReparaturDachwartungRouteImport.update({
  id: '/reparatur-dachwartung',
  path: '/reparatur-dachwartung',
  getParentRoute: () => rootRouteImport,
} as any)
const SekurantenRoute = SekurantenRouteImport.update({
  id: '/sekuranten',
  path: '/sekuranten',
  getParentRoute: () => rootRouteImport,
} as any)
const SpenglereiRoute = SpenglereiRouteImport.update({
  id: '/spenglerei',
  path: '/spenglerei',
  getParentRoute: () => rootRouteImport,
} as any)
const TaubenabwehrRoute = TaubenabwehrRouteImport.update({
  id: '/taubenabwehr',
  path: '/taubenabwehr',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/betrieb': typeof BetriebRoute
  '/dachbegruenung': typeof DachbegruenungRoute
  '/dachdeckerei': typeof DachdeckereiRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/karriere': typeof KarriereRoute
  '/kontakt': typeof KontaktRoute
  '/reparatur-dachwartung': typeof ReparaturDachwartungRoute
  '/sekuranten': typeof SekurantenRoute
  '/spenglerei': typeof SpenglereiRoute
  '/taubenabwehr': typeof TaubenabwehrRoute
  '/team': typeof TeamRoute
  '/ueber-uns': typeof UeberUnsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/betrieb': typeof BetriebRoute
  '/dachbegruenung': typeof DachbegruenungRoute
  '/dachdeckerei': typeof DachdeckereiRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/karriere': typeof KarriereRoute
  '/kontakt': typeof KontaktRoute
  '/reparatur-dachwartung': typeof ReparaturDachwartungRoute
  '/sekuranten': typeof SekurantenRoute
  '/spenglerei': typeof SpenglereiRoute
  '/taubenabwehr': typeof TaubenabwehrRoute
  '/team': typeof TeamRoute
  '/ueber-uns': typeof UeberUnsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/betrieb': typeof BetriebRoute
  '/dachbegruenung': typeof DachbegruenungRoute
  '/dachdeckerei': typeof DachdeckereiRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/karriere': typeof KarriereRoute
  '/kontakt': typeof KontaktRoute
  '/reparatur-dachwartung': typeof ReparaturDachwartungRoute
  '/sekuranten': typeof SekurantenRoute
  '/spenglerei': typeof SpenglereiRoute
  '/taubenabwehr': typeof TaubenabwehrRoute
  '/team': typeof TeamRoute
  '/ueber-uns': typeof UeberUnsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/betrieb'
    | '/dachbegruenung'
    | '/dachdeckerei'
    | '/datenschutz'
    | '/impressum'
    | '/karriere'
    | '/kontakt'
    | '/reparatur-dachwartung'
    | '/sekuranten'
    | '/spenglerei'
    | '/taubenabwehr'
    | '/team'
    | '/ueber-uns'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/betrieb'
    | '/dachbegruenung'
    | '/dachdeckerei'
    | '/datenschutz'
    | '/impressum'
    | '/karriere'
    | '/kontakt'
    | '/reparatur-dachwartung'
    | '/sekuranten'
    | '/spenglerei'
    | '/taubenabwehr'
    | '/team'
    | '/ueber-uns'
  id:
    | '__root__'
    | '/'
    | '/betrieb'
    | '/dachbegruenung'
    | '/dachdeckerei'
    | '/datenschutz'
    | '/impressum'
    | '/karriere'
    | '/kontakt'
    | '/reparatur-dachwartung'
    | '/sekuranten'
    | '/spenglerei'
    | '/taubenabwehr'
    | '/team'
    | '/ueber-uns'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BetriebRoute: typeof BetriebRoute
  DachbegruenungRoute: typeof DachbegruenungRoute
  DachdeckereiRoute: typeof DachdeckereiRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  KarriereRoute: typeof KarriereRoute
  KontaktRoute: typeof KontaktRoute
  ReparaturDachwartungRoute: typeof ReparaturDachwartungRoute
  SekurantenRoute: typeof SekurantenRoute
  SpenglereiRoute: typeof SpenglereiRoute
  TaubenabwehrRoute: typeof TaubenabwehrRoute
  TeamRoute: typeof TeamRoute
  UeberUnsRoute: typeof UeberUnsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/betrieb': {
      id: '/betrieb'
      path: '/betrieb'
      fullPath: '/betrieb'
      preLoaderRoute: typeof BetriebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dachbegruenung': {
      id: '/dachbegruenung'
      path: '/dachbegruenung'
      fullPath: '/dachbegruenung'
      preLoaderRoute: typeof DachbegruenungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dachdeckerei': {
      id: '/dachdeckerei'
      path: '/dachdeckerei'
      fullPath: '/dachdeckerei'
      preLoaderRoute: typeof DachdeckereiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karriere': {
      id: '/karriere'
      path: '/karriere'
      fullPath: '/karriere'
      preLoaderRoute: typeof KarriereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reparatur-dachwartung': {
      id: '/reparatur-dachwartung'
      path: '/reparatur-dachwartung'
      fullPath: '/reparatur-dachwartung'
      preLoaderRoute: typeof ReparaturDachwartungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sekuranten': {
      id: '/sekuranten'
      path: '/sekuranten'
      fullPath: '/sekuranten'
      preLoaderRoute: typeof SekurantenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spenglerei': {
      id: '/spenglerei'
      path: '/spenglerei'
      fullPath: '/spenglerei'
      preLoaderRoute: typeof SpenglereiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taubenabwehr': {
      id: '/taubenabwehr'
      path: '/taubenabwehr'
      fullPath: '/taubenabwehr'
      preLoaderRoute: typeof TaubenabwehrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BetriebRoute: BetriebRoute,
  DachbegruenungRoute: DachbegruenungRoute,
  DachdeckereiRoute: DachdeckereiRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  KarriereRoute: KarriereRoute,
  KontaktRoute: KontaktRoute,
  ReparaturDachwartungRoute: ReparaturDachwartungRoute,
  SekurantenRoute: SekurantenRoute,
  SpenglereiRoute: SpenglereiRoute,
  TaubenabwehrRoute: TaubenabwehrRoute,
  TeamRoute: TeamRoute,
  UeberUnsRoute: UeberUnsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
